/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.btoy.kafka_avro.dto.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class EmployeeAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2069199849023589765L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EmployeeAvro\",\"namespace\":\"com.btoy.kafka_avro.dto.avro\",\"fields\":[{\"name\":\"firstName\",\"type\":\"string\"},{\"name\":\"lastName\",\"type\":\"string\"},{\"name\":\"age\",\"type\":\"int\"},{\"name\":\"email\",\"type\":\"string\"},{\"name\":\"dbo\",\"type\":{\"type\":\"long\",\"logicalType\":\"time-millis\"}},{\"name\":\"employeeType\",\"type\":{\"type\":\"enum\",\"name\":\"EmployeeTypeAvro\",\"symbols\":[\"PENDING_TYPE_ASSIGNMENT\",\"ASSIGNING\",\"DATA_ANALYST\",\"BACKEND_DEVELOPER\",\"FULL_STACK_DEVELOPER\",\"AI_DEVELOPER\"]}},{\"name\":\"isActive\",\"type\":\"boolean\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EmployeeAvro> ENCODER =
      new BinaryMessageEncoder<EmployeeAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EmployeeAvro> DECODER =
      new BinaryMessageDecoder<EmployeeAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<EmployeeAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<EmployeeAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EmployeeAvro>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this EmployeeAvro to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a EmployeeAvro from a ByteBuffer. */
  public static EmployeeAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence firstName;
  @Deprecated public java.lang.CharSequence lastName;
  @Deprecated public int age;
  @Deprecated public java.lang.CharSequence email;
  @Deprecated public long dbo;
  @Deprecated public com.btoy.kafka_avro.dto.avro.EmployeeTypeAvro employeeType;
  @Deprecated public boolean isActive;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>builder()</code>.
   */
  public EmployeeAvro() {}

  /**
   * All-args constructor.
   * @param firstName The new value for firstName
   * @param lastName The new value for lastName
   * @param age The new value for age
   * @param email The new value for email
   * @param dbo The new value for dbo
   * @param employeeType The new value for employeeType
   * @param isActive The new value for isActive
   */
  public EmployeeAvro(java.lang.CharSequence firstName, java.lang.CharSequence lastName, java.lang.Integer age, java.lang.CharSequence email, java.lang.Long dbo, com.btoy.kafka_avro.dto.avro.EmployeeTypeAvro employeeType, java.lang.Boolean isActive) {
    this.firstName = firstName;
    this.lastName = lastName;
    this.age = age;
    this.email = email;
    this.dbo = dbo;
    this.employeeType = employeeType;
    this.isActive = isActive;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return firstName;
    case 1: return lastName;
    case 2: return age;
    case 3: return email;
    case 4: return dbo;
    case 5: return employeeType;
    case 6: return isActive;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: firstName = (java.lang.CharSequence)value$; break;
    case 1: lastName = (java.lang.CharSequence)value$; break;
    case 2: age = (java.lang.Integer)value$; break;
    case 3: email = (java.lang.CharSequence)value$; break;
    case 4: dbo = (java.lang.Long)value$; break;
    case 5: employeeType = (com.btoy.kafka_avro.dto.avro.EmployeeTypeAvro)value$; break;
    case 6: isActive = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'firstName' field.
   * @return The value of the 'firstName' field.
   */
  public java.lang.CharSequence getFirstName() {
    return firstName;
  }

  /**
   * Sets the value of the 'firstName' field.
   * @param value the value to set.
   */
  public void setFirstName(java.lang.CharSequence value) {
    this.firstName = value;
  }

  /**
   * Gets the value of the 'lastName' field.
   * @return The value of the 'lastName' field.
   */
  public java.lang.CharSequence getLastName() {
    return lastName;
  }

  /**
   * Sets the value of the 'lastName' field.
   * @param value the value to set.
   */
  public void setLastName(java.lang.CharSequence value) {
    this.lastName = value;
  }

  /**
   * Gets the value of the 'age' field.
   * @return The value of the 'age' field.
   */
  public java.lang.Integer getAge() {
    return age;
  }

  /**
   * Sets the value of the 'age' field.
   * @param value the value to set.
   */
  public void setAge(java.lang.Integer value) {
    this.age = value;
  }

  /**
   * Gets the value of the 'email' field.
   * @return The value of the 'email' field.
   */
  public java.lang.CharSequence getEmail() {
    return email;
  }

  /**
   * Sets the value of the 'email' field.
   * @param value the value to set.
   */
  public void setEmail(java.lang.CharSequence value) {
    this.email = value;
  }

  /**
   * Gets the value of the 'dbo' field.
   * @return The value of the 'dbo' field.
   */
  public java.lang.Long getDbo() {
    return dbo;
  }

  /**
   * Sets the value of the 'dbo' field.
   * @param value the value to set.
   */
  public void setDbo(java.lang.Long value) {
    this.dbo = value;
  }

  /**
   * Gets the value of the 'employeeType' field.
   * @return The value of the 'employeeType' field.
   */
  public com.btoy.kafka_avro.dto.avro.EmployeeTypeAvro getEmployeeType() {
    return employeeType;
  }

  /**
   * Sets the value of the 'employeeType' field.
   * @param value the value to set.
   */
  public void setEmployeeType(com.btoy.kafka_avro.dto.avro.EmployeeTypeAvro value) {
    this.employeeType = value;
  }

  /**
   * Gets the value of the 'isActive' field.
   * @return The value of the 'isActive' field.
   */
  public java.lang.Boolean getIsActive() {
    return isActive;
  }

  /**
   * Sets the value of the 'isActive' field.
   * @param value the value to set.
   */
  public void setIsActive(java.lang.Boolean value) {
    this.isActive = value;
  }

  /**
   * Creates a new EmployeeAvro RecordBuilder.
   * @return A new EmployeeAvro RecordBuilder
   */
  public static com.btoy.kafka_avro.dto.avro.EmployeeAvro.Builder builder() {
    return new com.btoy.kafka_avro.dto.avro.EmployeeAvro.Builder();
  }

  /**
   * Creates a new EmployeeAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EmployeeAvro RecordBuilder
   */
  public static com.btoy.kafka_avro.dto.avro.EmployeeAvro.Builder builder(com.btoy.kafka_avro.dto.avro.EmployeeAvro.Builder other) {
    return new com.btoy.kafka_avro.dto.avro.EmployeeAvro.Builder(other);
  }

  /**
   * Creates a new EmployeeAvro RecordBuilder by copying an existing EmployeeAvro instance.
   * @param other The existing instance to copy.
   * @return A new EmployeeAvro RecordBuilder
   */
  public static com.btoy.kafka_avro.dto.avro.EmployeeAvro.Builder builder(com.btoy.kafka_avro.dto.avro.EmployeeAvro other) {
    return new com.btoy.kafka_avro.dto.avro.EmployeeAvro.Builder(other);
  }

  /**
   * RecordBuilder for EmployeeAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EmployeeAvro>
    implements org.apache.avro.data.RecordBuilder<EmployeeAvro> {

    private java.lang.CharSequence firstName;
    private java.lang.CharSequence lastName;
    private int age;
    private java.lang.CharSequence email;
    private long dbo;
    private com.btoy.kafka_avro.dto.avro.EmployeeTypeAvro employeeType;
    private boolean isActive;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.btoy.kafka_avro.dto.avro.EmployeeAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.firstName)) {
        this.firstName = data().deepCopy(fields()[0].schema(), other.firstName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lastName)) {
        this.lastName = data().deepCopy(fields()[1].schema(), other.lastName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.age)) {
        this.age = data().deepCopy(fields()[2].schema(), other.age);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.email)) {
        this.email = data().deepCopy(fields()[3].schema(), other.email);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.dbo)) {
        this.dbo = data().deepCopy(fields()[4].schema(), other.dbo);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.employeeType)) {
        this.employeeType = data().deepCopy(fields()[5].schema(), other.employeeType);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.isActive)) {
        this.isActive = data().deepCopy(fields()[6].schema(), other.isActive);
        fieldSetFlags()[6] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing EmployeeAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.btoy.kafka_avro.dto.avro.EmployeeAvro other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.firstName)) {
        this.firstName = data().deepCopy(fields()[0].schema(), other.firstName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lastName)) {
        this.lastName = data().deepCopy(fields()[1].schema(), other.lastName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.age)) {
        this.age = data().deepCopy(fields()[2].schema(), other.age);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.email)) {
        this.email = data().deepCopy(fields()[3].schema(), other.email);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.dbo)) {
        this.dbo = data().deepCopy(fields()[4].schema(), other.dbo);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.employeeType)) {
        this.employeeType = data().deepCopy(fields()[5].schema(), other.employeeType);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.isActive)) {
        this.isActive = data().deepCopy(fields()[6].schema(), other.isActive);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'firstName' field.
      * @return The value.
      */
    public java.lang.CharSequence getFirstName() {
      return firstName;
    }

    /**
      * Sets the value of the 'firstName' field.
      * @param value The value of 'firstName'.
      * @return This builder.
      */
    public com.btoy.kafka_avro.dto.avro.EmployeeAvro.Builder setFirstName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.firstName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'firstName' field has been set.
      * @return True if the 'firstName' field has been set, false otherwise.
      */
    public boolean hasFirstName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'firstName' field.
      * @return This builder.
      */
    public com.btoy.kafka_avro.dto.avro.EmployeeAvro.Builder clearFirstName() {
      firstName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastName' field.
      * @return The value.
      */
    public java.lang.CharSequence getLastName() {
      return lastName;
    }

    /**
      * Sets the value of the 'lastName' field.
      * @param value The value of 'lastName'.
      * @return This builder.
      */
    public com.btoy.kafka_avro.dto.avro.EmployeeAvro.Builder setLastName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.lastName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'lastName' field has been set.
      * @return True if the 'lastName' field has been set, false otherwise.
      */
    public boolean hasLastName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'lastName' field.
      * @return This builder.
      */
    public com.btoy.kafka_avro.dto.avro.EmployeeAvro.Builder clearLastName() {
      lastName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'age' field.
      * @return The value.
      */
    public java.lang.Integer getAge() {
      return age;
    }

    /**
      * Sets the value of the 'age' field.
      * @param value The value of 'age'.
      * @return This builder.
      */
    public com.btoy.kafka_avro.dto.avro.EmployeeAvro.Builder setAge(int value) {
      validate(fields()[2], value);
      this.age = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'age' field has been set.
      * @return True if the 'age' field has been set, false otherwise.
      */
    public boolean hasAge() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'age' field.
      * @return This builder.
      */
    public com.btoy.kafka_avro.dto.avro.EmployeeAvro.Builder clearAge() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'email' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmail() {
      return email;
    }

    /**
      * Sets the value of the 'email' field.
      * @param value The value of 'email'.
      * @return This builder.
      */
    public com.btoy.kafka_avro.dto.avro.EmployeeAvro.Builder setEmail(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.email = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'email' field has been set.
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'email' field.
      * @return This builder.
      */
    public com.btoy.kafka_avro.dto.avro.EmployeeAvro.Builder clearEmail() {
      email = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'dbo' field.
      * @return The value.
      */
    public java.lang.Long getDbo() {
      return dbo;
    }

    /**
      * Sets the value of the 'dbo' field.
      * @param value The value of 'dbo'.
      * @return This builder.
      */
    public com.btoy.kafka_avro.dto.avro.EmployeeAvro.Builder setDbo(long value) {
      validate(fields()[4], value);
      this.dbo = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'dbo' field has been set.
      * @return True if the 'dbo' field has been set, false otherwise.
      */
    public boolean hasDbo() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'dbo' field.
      * @return This builder.
      */
    public com.btoy.kafka_avro.dto.avro.EmployeeAvro.Builder clearDbo() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'employeeType' field.
      * @return The value.
      */
    public com.btoy.kafka_avro.dto.avro.EmployeeTypeAvro getEmployeeType() {
      return employeeType;
    }

    /**
      * Sets the value of the 'employeeType' field.
      * @param value The value of 'employeeType'.
      * @return This builder.
      */
    public com.btoy.kafka_avro.dto.avro.EmployeeAvro.Builder setEmployeeType(com.btoy.kafka_avro.dto.avro.EmployeeTypeAvro value) {
      validate(fields()[5], value);
      this.employeeType = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'employeeType' field has been set.
      * @return True if the 'employeeType' field has been set, false otherwise.
      */
    public boolean hasEmployeeType() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'employeeType' field.
      * @return This builder.
      */
    public com.btoy.kafka_avro.dto.avro.EmployeeAvro.Builder clearEmployeeType() {
      employeeType = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'isActive' field.
      * @return The value.
      */
    public java.lang.Boolean getIsActive() {
      return isActive;
    }

    /**
      * Sets the value of the 'isActive' field.
      * @param value The value of 'isActive'.
      * @return This builder.
      */
    public com.btoy.kafka_avro.dto.avro.EmployeeAvro.Builder setIsActive(boolean value) {
      validate(fields()[6], value);
      this.isActive = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'isActive' field has been set.
      * @return True if the 'isActive' field has been set, false otherwise.
      */
    public boolean hasIsActive() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'isActive' field.
      * @return This builder.
      */
    public com.btoy.kafka_avro.dto.avro.EmployeeAvro.Builder clearIsActive() {
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EmployeeAvro build() {
      try {
        EmployeeAvro record = new EmployeeAvro();
        record.firstName = fieldSetFlags()[0] ? this.firstName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.lastName = fieldSetFlags()[1] ? this.lastName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.age = fieldSetFlags()[2] ? this.age : (java.lang.Integer) defaultValue(fields()[2]);
        record.email = fieldSetFlags()[3] ? this.email : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.dbo = fieldSetFlags()[4] ? this.dbo : (java.lang.Long) defaultValue(fields()[4]);
        record.employeeType = fieldSetFlags()[5] ? this.employeeType : (com.btoy.kafka_avro.dto.avro.EmployeeTypeAvro) defaultValue(fields()[5]);
        record.isActive = fieldSetFlags()[6] ? this.isActive : (java.lang.Boolean) defaultValue(fields()[6]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EmployeeAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<EmployeeAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EmployeeAvro>
    READER$ = (org.apache.avro.io.DatumReader<EmployeeAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
