/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.btoy.kafka_avro.dto.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum EmployeeTypeAvro {
  PENDING_TYPE_ASSIGNMENT, ASSIGNING, DATA_ANALYST, BACKEND_DEVELOPER, FULL_STACK_DEVELOPER, AI_DEVELOPER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EmployeeTypeAvro\",\"namespace\":\"com.btoy.kafka_avro.dto.avro\",\"symbols\":[\"PENDING_TYPE_ASSIGNMENT\",\"ASSIGNING\",\"DATA_ANALYST\",\"BACKEND_DEVELOPER\",\"FULL_STACK_DEVELOPER\",\"AI_DEVELOPER\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
