/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.btoy.kafka_avro.dto.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum UserType {
  BEGINNER, MEDIUM, VETERAN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EmployeeType\",\"namespace\":\"com.btoy.kafka_avro.dto\",\"symbols\":[\"BEGINNER\",\"MEDIUM\",\"VETERAN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
