version: "3.8"
services:
  kafka1:
    image: vinsdocker/kafka
    container_name: kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_CLUSTER_ID: OTMwNzFhYTY1ODNiNGE5OT
    volumes:
    - ./props/server.properties:/kafka/config/kraft/server.properties
    - ./data:/tmp/kafka-logs

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8085:8085"
    depends_on:
      - kafka1
    environment:
      KAFKA_CLUSTERS_0_NAME: sboot-kafka-app
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092
      
